"""HTML templates for the showcase site.

Plain string templates with ``__TOKEN__`` placeholders (no template engine
dependency, and no brace-escaping headaches in CSS/JS). All dynamic data is
embedded as JSON inside each page, so the site works from file:// and GitHub
Pages alike with zero server requirements.
"""

_BASE_CSS = """
:root {
  --coral: #FF4D6D; --ink: #181818; --teal: #1FB6A6; --blue: #2D5BFF;
  --yellow: #FFC23C; --cream: #FBF7F0; --sand: #F3E9D8;
}
* { box-sizing: border-box; }
body {
  margin: 0; background: var(--cream); color: var(--ink);
  font-family: "JetBrains Mono", "SFMono-Regular", Consolas, monospace;
  line-height: 1.55;
}
h1, h2, h3 { font-family: "Space Grotesk", sans-serif; letter-spacing: -0.02em; }
.wrap { max-width: 980px; margin: 0 auto; padding: 2.5rem 1.25rem 4rem; }
.masthead { border-bottom: 3px solid var(--ink); padding-bottom: 1.2rem; margin-bottom: 2rem; }
.masthead h1 { font-size: 2.4rem; margin: 0 0 0.3rem; }
.masthead .sub { color: #555; }
.badge {
  display: inline-block; background: var(--coral); color: #fff;
  border: 2px solid var(--ink); padding: 0.15rem 0.7rem; font-weight: 700;
  font-size: 0.8rem; margin-right: 0.4rem;
}
.badge.teal { background: var(--teal); }
.badge.blue { background: var(--blue); }
.card {
  background: #fff; border: 2px solid var(--ink); padding: 1.2rem 1.4rem;
  margin-bottom: 1.4rem;
}
.card h2, .card h3 { margin-top: 0; }
a.topic-link { color: inherit; text-decoration: none; display: block; }
a.topic-link:hover .card { background: var(--sand); }
.section-title {
  display: inline-block; background: var(--coral); color: #fff;
  border: 2px solid var(--ink); padding: 0.3rem 1.1rem; margin: 2rem 0 1rem;
  font-size: 1.15rem; font-weight: 700; font-family: "Space Grotesk", sans-serif;
}
.note { background: var(--sand); border: 2px solid var(--ink); padding: 0.8rem 1rem; margin: 0.8rem 0; }
.meta { color: #555; font-size: 0.85rem; }
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1.2rem; }
.stat { text-align: center; padding: 0.8rem; }
.stat .num { font-size: 1.9rem; font-weight: 700; color: var(--coral); }
.stat .lbl { font-size: 0.8rem; text-transform: uppercase; }
.comment { border-left: 4px solid var(--teal); padding: 0.5rem 1rem; margin: 0.8rem 0; background: #fff; border-top: 1px solid #eee; }
.comment.negative { border-left-color: var(--coral); }
.comment.neutral { border-left-color: var(--yellow); }
.comment .meta a { color: var(--blue); }
.insights li { margin-bottom: 0.5rem; }
.sentibar { display: flex; height: 26px; border: 2px solid var(--ink); overflow: hidden; margin: 0.6rem 0; }
.sentibar div { height: 100%; }
.sentibar .pos { background: var(--teal); }
.sentibar .neu { background: var(--yellow); }
.sentibar .neg { background: var(--coral); }
.legend { font-size: 0.8rem; color: #555; }
.chart { width: 100%; }
footer { margin-top: 3rem; color: #777; font-size: 0.8rem; border-top: 2px solid var(--ink); padding-top: 1rem; }
"""

_FONTS = (
    '<link rel="preconnect" href="https://fonts.googleapis.com">'
    '<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;700'
    '&family=JetBrains+Mono:wght@400;700&display=swap" rel="stylesheet">'
)

_VEGA = (
    '<script src="https://cdn.jsdelivr.net/npm/vega@5"></script>'
    '<script src="https://cdn.jsdelivr.net/npm/vega-lite@5"></script>'
    '<script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>'
)

INDEX_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>__SITE_TITLE__</title>
""" + _FONTS + """
<style>""" + _BASE_CSS + """</style>
</head>
<body>
<div class="wrap">
  <div class="masthead">
    <h1>__SITE_TITLE__</h1>
    <div class="sub">__SITE_SUBTITLE__</div>
  </div>
  __TOPIC_CARDS__
  <footer>Generated by RedditPulse on __GENERATED_AT__ · Data from Reddit public archives</footer>
</div>
</body>
</html>
"""

TOPIC_CARD_TEMPLATE = """
<a class="topic-link" href="topics/__SLUG__.html">
  <div class="card">
    <h2>__TITLE__</h2>
    <p>__DESCRIPTION__</p>
    <div class="sentibar" title="positive / neutral / negative">
      <div class="pos" style="width:__PCT_POS__%"></div>
      <div class="neu" style="width:__PCT_NEU__%"></div>
      <div class="neg" style="width:__PCT_NEG__%"></div>
    </div>
    <div class="legend">__PCT_POS__% positive · __PCT_NEU__% neutral · __PCT_NEG__% negative</div>
    <div class="meta">__COMMENT_COUNT__ comments analyzed · __RUN_AT__</div>
  </div>
</a>
"""

TOPIC_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>__TITLE__ — __SITE_TITLE__</title>
""" + _FONTS + _VEGA + """
<style>""" + _BASE_CSS + """</style>
</head>
<body>
<div class="wrap">
  <div class="masthead">
    <div class="meta"><a href="../index.html">← __SITE_TITLE__</a></div>
    <h1>__TITLE__</h1>
    <div class="sub">__DESCRIPTION__</div>
    <div style="margin-top:0.6rem">
      <span class="badge">__COMMENT_COUNT__ comments</span>
      <span class="badge teal">analyzed __RUN_AT__</span>
      __EXTRA_BADGES__
    </div>
  </div>
  <div id="sections"></div>
  <footer>Generated by RedditPulse on __GENERATED_AT__ · Data from Reddit public archives</footer>
</div>
<script id="payload" type="application/json">__PAYLOAD_JSON__</script>
<script>
const D = JSON.parse(document.getElementById("payload").textContent);
const root = document.getElementById("sections");
const VEGA_CONF = { background: "transparent",
  axis: { labelFont: "JetBrains Mono", titleFont: "JetBrains Mono" },
  legend: { labelFont: "JetBrains Mono", titleFont: "JetBrains Mono" } };

function el(html) {
  const div = document.createElement("div");
  div.innerHTML = html;
  return div;
}
function esc(s) {
  return String(s ?? "").replace(/[&<>"]/g,
    ch => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[ch]));
}
function section(title, note) {
  const wrap = el(`<div><div class="section-title">${esc(title)}</div></div>`);
  if (note) wrap.appendChild(el(`<div class="note">${esc(note)}</div>`));
  return wrap;
}
function chartDiv(parent) {
  const d = document.createElement("div");
  d.className = "chart";
  parent.appendChild(d);
  return d;
}

const RENDERERS = {
  sentiment(note) {
    const s = D.analysis.sentiment;
    const w = section("Sentiment", note);
    const total = s.total || 1;
    w.appendChild(el(`
      <div class="card"><div class="grid">
        <div class="stat"><div class="num">${s.positive}</div><div class="lbl">Positive</div></div>
        <div class="stat"><div class="num">${s.neutral}</div><div class="lbl">Neutral</div></div>
        <div class="stat"><div class="num">${s.negative}</div><div class="lbl">Negative</div></div>
        <div class="stat"><div class="num">${(s.average_compound ?? 0).toFixed(2)}</div><div class="lbl">Avg compound</div></div>
      </div>
      <div class="sentibar">
        <div class="pos" style="width:${100 * s.positive / total}%"></div>
        <div class="neu" style="width:${100 * s.neutral / total}%"></div>
        <div class="neg" style="width:${100 * s.negative / total}%"></div>
      </div>
      ${s.upvote_weighted ? `<div class="legend">Upvote-weighted: ${s.upvote_weighted.pct_positive}% positive ·
        ${s.upvote_weighted.pct_neutral}% neutral · ${s.upvote_weighted.pct_negative}% negative</div>` : ""}
      </div>`));
    return w;
  },
  themes(note) {
    const themes = (D.analysis.themes?.themes || []).slice(0, 10);
    if (!themes.length) return null;
    const w = section("Top themes", note);
    const card = el(`<div class="card"></div>`);
    w.appendChild(card);
    vegaEmbed(chartDiv(card), {
      $schema: "https://vega.github.io/schema/vega-lite/v5.json",
      data: { values: themes }, width: "container", height: themes.length * 32,
      mark: { type: "bar", color: "#2D5BFF" },
      encoding: {
        x: { field: "count", type: "quantitative", title: "Mentions" },
        y: { field: "theme", type: "nominal", sort: "-x", title: null },
        tooltip: [{ field: "theme" }, { field: "count" }, { field: "summary" }],
      }, config: VEGA_CONF,
    }, { actions: false });
    themes.forEach(t => card.appendChild(
      el(`<p><b>${esc(t.theme)}</b> — ${esc(t.summary || "")}</p>`)));
    return w;
  },
  emotions(note) {
    const emotions = (D.analysis.themes?.emotions || []).slice(0, 8);
    if (!emotions.length) return null;
    const w = section("Emotions", note);
    const card = el(`<div class="card"></div>`);
    w.appendChild(card);
    vegaEmbed(chartDiv(card), {
      $schema: "https://vega.github.io/schema/vega-lite/v5.json",
      data: { values: emotions }, width: "container", height: emotions.length * 32,
      mark: { type: "bar", color: "#FF6B4A" },
      encoding: {
        x: { field: "prevalence", type: "quantitative", title: "Prevalence" },
        y: { field: "emotion", type: "nominal", sort: "-x", title: null },
      }, config: VEGA_CONF,
    }, { actions: false });
    return w;
  },
  breakdown(note) {
    const b = D.analysis.themes?.subtopic_breakdown;
    if (!b || !b.categories?.length) return null;
    const w = section(b.dimension || "Breakdown", note);
    const card = el(`<div class="card"></div>`);
    w.appendChild(card);
    vegaEmbed(chartDiv(card), {
      $schema: "https://vega.github.io/schema/vega-lite/v5.json",
      data: { values: b.categories }, width: "container", height: b.categories.length * 32,
      mark: { type: "bar", color: "#7C5CFF" },
      encoding: {
        x: { field: "percentage", type: "quantitative", title: "%" },
        y: { field: "category", type: "nominal", sort: "-x", title: null },
      }, config: VEGA_CONF,
    }, { actions: false });
    return w;
  },
  opinions(note) {
    const ops = (D.analysis.themes?.opinions || []).slice(0, 8);
    if (!ops.length) return null;
    const w = section("Key opinions", note);
    const card = el(`<div class="card"></div>`);
    ops.forEach(o => card.appendChild(el(
      `<p><span class="badge ${o.strength === "strong" ? "" : "blue"}">${esc(o.strength || "?")}</span>
       ${esc(o.stance)}</p>`)));
    w.appendChild(card);
    return w;
  },
  insights(note) {
    const ins = D.analysis.themes?.key_insights || [];
    if (!ins.length) return null;
    const w = section("Key insights", note);
    const card = el(`<div class="card"><ul class="insights">
      ${ins.map(i => `<li>${esc(i)}</li>`).join("")}</ul></div>`);
    const c = D.analysis.themes?.controversy_level;
    if (c) {
      const text = typeof c === "object" ? `${c.level ?? "?"} — ${c.explanation ?? ""}` : c;
      card.appendChild(el(`<div class="note"><b>Controversy:</b> ${esc(text)}</div>`));
    }
    w.appendChild(card);
    return w;
  },
  trends(note) {
    const t = D.trends;
    if (!t || !t.points?.length) return null;
    const w = section("Sentiment over time", note);
    const card = el(`<div class="card"></div>`);
    w.appendChild(card);
    const long = [];
    t.points.forEach(p => {
      long.push({ period: p.period, kind: "% positive", value: p.pct_positive });
      long.push({ period: p.period, kind: "% negative", value: p.pct_negative });
    });
    vegaEmbed(chartDiv(card), {
      $schema: "https://vega.github.io/schema/vega-lite/v5.json",
      data: { values: long }, width: "container", height: 220,
      mark: { type: "line", point: true },
      encoding: {
        x: { field: "period", type: "ordinal", title: `By ${t.bucket}`,
             axis: { labelAngle: -45 } },
        y: { field: "value", type: "quantitative", title: "% of comments" },
        color: { field: "kind", title: null,
                 scale: { domain: ["% positive", "% negative"],
                          range: ["#1FB6A6", "#FF4D6D"] } },
      }, config: VEGA_CONF,
    }, { actions: false });
    vegaEmbed(chartDiv(card), {
      $schema: "https://vega.github.io/schema/vega-lite/v5.json",
      data: { values: t.points }, width: "container", height: 120,
      mark: { type: "bar", color: "#2D5BFF" },
      encoding: {
        x: { field: "period", type: "ordinal", title: null, axis: { labelAngle: -45 } },
        y: { field: "count", type: "quantitative", title: "Comments" },
      }, config: VEGA_CONF,
    }, { actions: false });
    return w;
  },
  top_comments(note) {
    const comments = D.top_comments || [];
    if (!comments.length) return null;
    const w = section("Voices from the thread", note);
    const card = el(`<div class="card"></div>`);
    comments.forEach(c => card.appendChild(el(`
      <div class="comment ${esc(c.label)}">
        <div>${esc(c.body)}</div>
        <div class="meta">▲ ${c.score} · r/${esc(c.subreddit)}
          ${c.permalink ? `· <a href="${esc(c.permalink)}" rel="nofollow">source</a>` : ""}</div>
      </div>`)));
    w.appendChild(card);
    return w;
  },
};

for (const s of D.sections) {
  const render = RENDERERS[s];
  if (!render) continue;
  const node = render(D.section_notes?.[s]);
  if (node) root.appendChild(node);
}
</script>
</body>
</html>
"""
